function rollpitchdes_equation = rollpitchdes_equation(t,yaw_des_var,ex_dd_var,ey_dd_var,x_dd_des_var,y_dd_des_var)
%ROLLPITCHDES_EQUATION
%    ROLLPITCHDES_EQUATION = ROLLPITCHDES_EQUATION(T,YAW_DES_VAR,EX_DD_VAR,EY_DD_VAR,X_DD_DES_VAR,Y_DD_DES_VAR)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Oct-2018 23:37:00

t2 = cos(yaw_des_var);
t3 = ex_dd_var+x_dd_des_var;
t4 = sin(yaw_des_var);
t5 = ey_dd_var+y_dd_des_var;
rollpitchdes_equation = [t2.*t5.*(-1.019716212977928e-1)+t3.*t4.*1.019716212977928e-1;t2.*t3.*1.019716212977928e-1+t4.*t5.*1.019716212977928e-1];
